### PR TITLE
Add SwipeRefreshLayout on MainActivity

### PR DESCRIPTION
**Pull request by shriakhilc**
Fixes Issue #1

### CODE REVIEW

**Comment by shriakhilc** [comment]
@steveswinsburg I'm not sure why your CI build is failing, but the app itself seems to be running perfectly. Could you take a look?

**Comment by steveswinsburg** [comment]
Yep will do, cheers.

**Comment by steveswinsburg** [comment]
@TheGamer007 I've fixed the travis build, do you want to merge master into this?

**Comment by shriakhilc** [comment]
Merged master into my fork. Shouldn't cause any issues now

**Comment by shriakhilc** [comment]
@steveswinsburg any problems with this? If not, it can be merged and the corresponding issue closed.

**Comment by steveswinsburg** [comment]
Thanks!

**Pull request merged**
